# Generated by Django 5.1.4 on 2024-12-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='course',
        ),
    ]
